### ISSUE TITLE
Sidebar doesn't show nesting properly for sub-sections

### ISSUE THREAD

**Issue by bertjwregeer** [Crunch-io/apidocs-sphinx#10]
http://crunch-api-docs.readthedocs.io/en/latest/endpoint-reference/endpoint-dataset.html

For example should show:

Catalog as having the following children:

- Catalog
    - GET
    - Drafts
    - PATCH
    - POST

And so forth, right now it looks like they are all at the same "level".

**Comment by dhandy2013** [comment]
Looking at the HTML source for that part of the table of contents on that page:
```html
<li class="toctree-l2 current"><a class="current reference internal" href="#">Datasets</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#catalog">Catalog</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#get">GET</a></li>
<li class="toctree-l4"><a class="reference internal" href="#drafts">Drafts</a></li>
<li class="toctree-l4"><a class="reference internal" href="#patch">PATCH</a><ul>
```
Notice that the tag nesting is correct. Inside the Catalog ``<li>`` element there is a nested ``<ul>`` which puts GET, Drafts, and PATCH in a deeper nesting as they should be. Also notice that the CSS class is correctly ``toctree-l4``, deeper than the parent which is ``toctree-l3``.
