### ISSUE TITLE
Change logo to use the new Crunch logo

### ISSUE THREAD

**Issue by jonkeane** [Crunch-io/apidocs-sphinx#3]
The logo in the upper left is our old one, we should swap it out for the new one (https://github.com/Crunch-io/ta-da/blob/master/img/crunch_logo.svg not sure that’s the correct source for those assests, but it should work)

**Comment by jimfulton** [comment]
I've updated to use the new SVG.  I suspect we should use a PNG for this. I'll change to use a PNG if someone gives me one. :)
