### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by jonkeane** [Crunch-io/apidocs-sphinx#5]
Is it possible to have syntax highlighting on the code? The old docs have it, and I know there are plugins that allow it in general.

**Comment by jonkeane** [comment]
On second glance, it looks like there is some highlighting, it's just a bit more subtle?

**Comment by jimfulton** [comment]
Yes, it is more subtle.

This is probably configurable. If we think we want it to be less subtle, we can probably configure it to be.  

I propose not to hold the switch to the new docs for this, so I'm closing this issue. If you disagree, then please reopen.

If you want to look at configuring the highlighting after the switch, please create a pivotal issue.
